### PR TITLE
Feat/Overview screen UI

### LINKED ISSUE #61: Test Overview screen

### LINKED ISSUE #63: Implement Overview Screen to match Figma mockup

### PR DESCRIPTION
**Pull request by 1andreea26**
## Summary
Closes #63 and #61.

This PR provides the final version of the Overview Screen which now contains the trips as Cards, and once you click on a Card, it redirects you to the Schedule Screen (to be implemented). Furthermore, it displays a picture set by default (currently the logo of the app), the trip name, the start and end dates and boxes with the first letter of the name of all participants to your trip (to be changed into users in the future). 

Furthermore, this PR also adds a participant list variable inside AddTrip, to avoid having participants with an empty string as a name (which was causing a bug displaying the correct number of participants in the Card composable).

## Changes

- **Screens/UI:** Overview Screen, AddTrip Screen
- **Bug Fixes/Improvements:** Improves the AddTrip screen, which now, in case there are no participants added, provides an emptyList() instead of an empty string.

## Checklist

- [X] This PR resolves #63  and #61 .
- [X] Tests have been added for new functionality.
- [X] Screenshots or UI changes have been attached (if applicable).

##  Testing

- **Manual Testing:**
    - [X] Tested on emulator / physical device.
- **Unit Tests**
    - [X] Added units tests for this

##  Related Issues/Tickets

Closes #61 and #63.

## Screenshots (if applicable)

Screenshot 2024-10-17 at 15 54 24

### CODE REVIEW

**Review by eleonoraka — APPROVED** [review]
Everything looks fine to me. Good job!

**Comment by g0g05arui** [comment]
A quick comment: The participants to a trip is a list of userIds. So in the future we will have to change this implementation after we will be able to correctly select the participants from the user's friends.

**Comment by 1andreea26** [comment]
> A quick comment: The participants to a trip is a list of userIds. So in the future we will have to change this implementation after we will be able to correctly select the participants from the user's friends.
> 
> Thus, the circle "profile pictures" will change then.

Thank you for the comment.I will add this as a draft to PB, so we can keep it in mind.

**Comment by 1andreea26** [comment]
> Everything looks fine to me. Good job!

Thanks!

**Pull request merged**
