### PR TITLE
Revert "Test: image from gallery"

### PR DESCRIPTION
**Pull request by mirceagavrizi**
Reverts swent-t16/Voyageur#226

### CODE REVIEW

**Review by 1andreea26 — APPROVED** [review]
I will approve. Thank you for rectifying this!

**Comment by 1andreea26** [comment]
Next time it could be great if you could develop a bit more the description, say why we need this revert (In this case you told me f2f, but it would be useful for the others to know as well).

**Comment by mirceagavrizi** [comment]
Good point, I will also explain here. These tests needed to be updated but then we realised that they already exist in other files, i.e. AddTripTest and EditProfileTest, so there is no need for them. Thank you for understanding.

**Comment by 1andreea26** [comment]
> Good point, I will also explain here. These tests needed to be updated but then we realised that they already exist in other files, i.e. AddTripTest and EditProfileTest, so there is no need for them. Thank you for understanding.

Thanks for explaining! I think it will now be more clear for the others. Don't forget to delete the branch!

**Pull request merged**
