### PR TITLE
Improve participants selection and show trips you are participating in

### LINKED ISSUE #181: Fix participants field

### LINKED ISSUE #182: See the trips where you're added as a participant

### PR DESCRIPTION
**Pull request by g0g05arui**
## Summary

In this PR I solved #181 and #182.
So now after you add a trip you can add participants using a dropdown menu. If somebody else added you as a participant, you will be able to see that trip as well on your overview screen.

## Changes

- **Bug Fixes/Improvements:** Bugfix regarding the UI

## Checklist

Ensure all / most of these are checked before the pull request is submitted.
- [x] This PR resolves #181 and resolves #182
- [x] Tests have been added for new functionality.

##  Testing
- **Manual Testing:**
    - [x] Tested on emulator / physical device.

### CODE REVIEW

**Review by 1andreea26 — APPROVED** [review]
This looks really good Mihai! I have nothing to add, your code is well-structured and using StateFlow for the contacts adheres nicely to the MVVM pattern. Moreover, you have added tests and your code reaches >80% line coverage. I will approve this. :)

**Comment by 1andreea26** [comment]
One quick thing which I noticed when I was checking out your work. For an ongoing trip, the Settings Screen doesn't allow you to edit as the start date is in the past. We should think about and define the behaviour of our app in this case. 
If you agree, I'll create an issue about this. I attached a screen-recording below to show you what I mean: 

https://github.com/user-attachments/assets/c2f3c63b-e1d0-4890-abb1-5e25f251617b

**Comment by g0g05arui** [comment]
Hmm, good catch. What would be the expected behavior then? Do we expect to modify both of the dates even in the past?
If so, I would assume we should also be able to create a trip in the past, at least the start date in the past.

**Comment by g0g05arui** [comment]
> I will approve this. :)

Thank you for the quick review

**Comment by 1andreea26** [comment]
> Hmm, good catch. What would be the expected behavior then? Do we expect to modify both of the dates even in the past? If so, I would assume we should also be able to create a trip in the past, at least the start date in the past.

I was thinking in Settings the user wouldn't be able to change the dates of an already existent trip, just the rest (name, participants, etc). Do you think that would work?

**Pull request merged**
